### ISSUE TITLE
chatbot example

### ISSUE THREAD

**Issue by esnible** [IBM/prompt-declaration-language#214]
**Describe the bug**
I Installed PDL using pip install prompt-declaration-language
I created chatbot.pdl using https://github.com/IBM/prompt-declaration-language?tab=readme-ov-file#chat
I ran `pdl chatbot.pdl`

The program could not answer a second question.  It failed with 
```
chatbot.pdl:9 - Error during model call: litellm.APIConnectionError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/Users/snible/junk_venv/lib/python3.12/site-packages/litellm/main.py", line 2705, in completion
    modified_prompt = ollama_pt(model=model, messages=messages)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snible/junk_venv/lib/python3.12/site-packages/litellm/llms/prompt_templates/factory.py", line 220, in ollama_pt
    for call in message["tool_calls"]:
                ~~~~~~~^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```

**To Reproduce**
See above.

Ask "why is the sky blue?" and "why is the sea blue?"

**Expected behavior**
A chatbot should accept input until the end.

**Environment**
Using prompt-declaration-language==0.1.0, installed with `pip install prompt-declaration-language`.  ollama version is 0.5.1, installed with `brew install ollama` and started with `/opt/homebrew/opt/ollama/bin/ollama serve`.

**Comment by vazirim** [comment]
@esnible Thank you so much for reporting this bug. I can reproduce it with PDL 0.1.0. 
This bug has been fixed in main (PR #212), we now remove parameters that have None values before sending a LLM request to LiteLLM.
